from python:3.8.3-alpine

run apk update
run apk add build-base python3-dev musl-dev gcc

workdir /tmp

copy requirements.txt /tmp
run python -m pip install -r requirements.txt

env flask_app=server.py

entrypoint web: gunicorn --bind 0.0.0.0:${port} server:app
